const jwt = require('jsonwebtoken');
const db = require('../lib/db');

const JWT_SECRET = process.env.JWT_SECRET || 'supersecretjwtkeyforaffiliateplatform123!';

/**
 * Authentication middleware to verify user identity and load profile role
 */
async function authenticate(req, res, next) {
  try {
    const authHeader = req.headers.authorization;
    let token = null;

    if (authHeader && authHeader.startsWith('Bearer ')) {
      token = authHeader.split(' ')[1];
    } else if (req.cookies && req.cookies.token) {
      token = req.cookies.token;
    }

    if (!token) {
      req.user = null;
      return next();
    }

    // Support mock tokens for quick local testing
    if (token === 'mock-admin-token') {
      const adminEmail = process.env.ADMIN_EMAIL || 'admin@affiliateplatform.in';
      req.user = {
        uid: 'mock_admin_123',
        email: adminEmail,
        displayName: 'Mock Administrator',
        role: 'admin'
      };
      return next();
    }

    if (token === 'mock-user-token') {
      req.user = {
        uid: 'mock_user_456',
        email: 'user@gmail.com',
        displayName: 'Mock Customer',
        role: 'user'
      };
      return next();
    }

    // Standard JWT Verification (for session tokens generated by backend login)
    try {
      const decoded = jwt.verify(token, JWT_SECRET);
      req.user = decoded;

      // Fetch latest role from the database
      const userProfile = await db.ref(`users/${decoded.uid}`).get();
      if (userProfile) {
        req.user.role = userProfile.role || 'user';
        req.user.displayName = userProfile.displayName || decoded.displayName;
      }
      return next();
    } catch (jwtErr) {
      // If JWT expired/failed, try decoding as Firebase token (if it contains firebase fields)
      // For development simplicity, we parse claims or do basic verification
      // A production server would run: firebaseAdmin.auth().verifyIdToken(token)
      console.warn('JWT verification failed, falling back to Firebase token extraction:', jwtErr.message);
      
      // Decoded token fallback
      const parts = token.split('.');
      if (parts.length === 3) {
        try {
          const payload = JSON.parse(Buffer.from(parts[1], 'base64').toString('utf-8'));
          if (payload.firebase) {
            const uid = payload.uid || payload.user_id;
            const email = payload.email;
            const displayName = payload.name || '';
            
            // Look up role in Database
            const userProfile = await db.ref(`users/${uid}`).get();
            const role = userProfile ? (userProfile.role || 'user') : 'user';

            req.user = {
              uid,
              email,
              displayName,
              role
            };
            return next();
          }
        } catch (parseErr) {
          console.error('Error parsing token fallback:', parseErr);
        }
      }
    }

    req.user = null;
    next();
  } catch (err) {
    console.error('Authentication middleware error:', err);
    req.user = null;
    next();
  }
}

/**
 * Require active user session
 */
function requireAuth(req, res, next) {
  if (!req.user) {
    return res.status(401).json({ error: 'Unauthorized: Authentication required' });
  }
  next();
}

/**
 * Require admin role access
 */
function requireAdmin(req, res, next) {
  if (!req.user) {
    return res.status(401).json({ error: 'Unauthorized: Authentication required' });
  }
  if (req.user.role !== 'admin') {
    return res.status(403).json({ error: 'Forbidden: Administrator privileges required' });
  }
  next();
}

module.exports = {
  authenticate,
  requireAuth,
  requireAdmin
};
